name: Publish to dockerhub

on:
  push:
    branches:
      - main
    paths-ignore:
      - website/**
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [18.18.2-alpine]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup QEmu so we can build multiplatform
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker meta configuration
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            unleashorg/unleash-server
          tags: |
            # only enabled for workflow dispatch except main (assume its a release):
            type=semver,pattern={{ version }},enable=${{ github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main' }}
            type=semver,pattern={{ major.minor }},enable=${{ github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main' }}
            type=semver,pattern={{ major }},enable=${{ github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main' }}
            # only enabled in main:
            type=edge,prefix=main-,suffix=-${{ matrix.version }},enable=${{ github.ref == 'refs/heads/main' }}
            # only enabled on workflow_dispatch:
            type=sha,suffix=-${{ matrix.version }},enable=${{ github.event_name == 'workflow_dispatch' }}
      - name: Login to docker hub
        run: echo "Ignored"
      - name: Build frontend
        run: |
          echo yarn --cwd ./frontend install
          echo yarn build:frontend
      - name: Build tag and push image to Docker hub
        run: |
          echo "docker/build-push-action@v5
          echo "tags: ${{ steps.meta.outputs.tags }}"
          echo "labels: ${{ steps.meta.outputs.labels }}"
          echo "build-args: NODE_VERSION=${{ matrix.version }}"
