name: Update version for version checker

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      version:
        description: "Which version should we set OSS to"
        type: 'string'
        required: true
  workflow_dispatch:
    inputs:
      version:
        description: "Which version should we set OSS to"
        type: 'string'
        required: true

jobs:
  update:
    if: ${{ !(contains(github.ref, 'beta') || contains(github.ref, 'alpha')) }}
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate Google IAM
        run: echo "Ignored"
      - name: Update version from manual dispatch
        if: ${{ inputs.version != '' }}
        run: |
          echo "version: ${{ inputs.version }} - distribution: oss"
